### ISSUE TITLE
Build system + es6 with 6to5?

### ISSUE THREAD

**Issue by mgcrea** [iamralpht/iamralpht.github.io#1]
Would you be interested in a working build system powered by [Gulp](http://gulpjs.com/)?
The build system could leverage [6to5](https://6to5.org) to build ES5 js from ES6 files.
I could tackle this and open a pull-request if you are interested.

Awesome work by the way. I've had quite some experience with web development on touch devices and the lack of momentum/physics touch interactions has always been one of the major missing thing for me.

**Comment by iamralpht** [comment]
That sounds great! I'd like to make gravitas.js and slalom.js git trees
before doing any serious work. I'll be tomorrow afternoon before I get to
that though. Would you be OK waiting until then?

**Comment by iamralpht** [comment]
So if you're still interested, I just got the gravitas.js tree to the point where it needs a build system (then I'll add examples and docs, etc). It's here: https://github.com/iamralpht/gravitas.js -- let me know if you're up for it :).

**Comment by gaearon** [comment]
I think it'd be better to avoid Gulp in favor of Webpack. Webpack also supports 6to5 transform via [6to5-loader](https://github.com/6to5/6to5-loader) but has a specific focus on JS. Gulp is more useful for orchestrating complex build process for a lot of tasks and dependencies between tasks, which we don't have here.

**Comment by iamralpht** [comment]
I've used webpack before and was pretty happy with it. For now I have a cheesy makefile calling browserify. I'd love to have gravitas available as an npm module for folks who are using something like webpack/browserify already, and to do uglified/minified releases.

I'm currently working on cleaning up slalom (using a proper gesture recognizer, etc) so it'll be a while before I get back to build systems. If someone wants to submit a pull request then that would be awesome :).

**Comment by gaearon** [comment]
I can do it. Ping me when you feel like it!

**Comment by iamralpht** [comment]
Cool, that sounds great--go for it! https://github.com/iamralpht/gravitas.js

**Comment by mgcrea** [comment]
@gaearon indeed gulp might seem overkill for simple 6to5+uglify transforms but a project like this should have unit tests (eg. karma+mocha/jasmine) and nice build-able docs, and gulp can easily cover all theses and more (code-quality, coverage, releases, etc.).

Anyway, I'm fine with webpack too ;-). I'm looking forward to try this in my Angular apps!

**Comment by gaearon** [comment]
https://github.com/iamralpht/gravitas.js/pull/2
